const Map<String, String> viVN = {
  'new_reminder': 'Thêm nhắc nhở',
  'add_list': 'Thêm nhóm',
  'done': 'Xong',
  'groups': 'Danh sách nhóm',
  'group': 'Nhóm',
  'details': 'Chi tiết',
  'priority': 'Ưu tiên',
  'none': 'Không',
  'low': 'Thấp',
  'medium': 'Trung bình',
  'high': 'Cao',
  'date': 'Ngày',
  'time': 'Thời gian',
};